Private_events
MarkoNS1990/private_events pull request #1
Opened 2021-04-30 20:25 UTC by MarkoNS1990

🟢 In this project we created a simple website similar to Eventbrite where users login before creating events. Users can also attend other users events. 🟢

2021-04-30 22:23 UTC, mricanho requested changes
# 🔴  Changes Required 🔴  

Hello @MarkoNS1990 @mgunduz1, you did a great job with your private events, the website it's fully functional and that's something that we need to celebrate🔥, just a few changes are required:

### General
- [ ]  **There's a bug, when an event is completed(past event), and a random user open the event, the user can join the event even if this is a past event, kindly fix this** 
- [x] **The "Home" navigation link must be present all the time in order to return to the main page at any moment**

### Controllers
- [x] **In the create action, you need to use #[build ](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/build_method_requirement.png)method on association, i.e. `current_user.events.build(event_params)`**
- [x] **You are taking the expired and future events from the scope to display them in the views, but you actually need to create in the [Index ](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png)action a lists past events(or expired_events), i.e. `@past_events = Event.previous_events` the same with future events**

### Tests

- [ ] **You need to create tests for your [models](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/unit_tests_requirement.png), "models have unit tests for validations and associations"**
- [ ] **Double check the configuration of your RSpec, right now none of the tests are running**

It's a lot, but you are so close to finish this project, and it was a really good first try, you got this.

![you can do it](https://user-images.githubusercontent.com/60631456/116759728-af0fa400-a9d8-11eb-85ab-3dbee9df6e62.gif)


You can contact me on slack if you have any questions just search for me as @ Miguel Ricaño.

### 💻 👩🏽‍💻  Happy Coding!👨🏽‍💻  🖥️

2021-05-02 16:59 UTC, enaburekhan approved these changes
# Status: Approve:heavy_check_mark:
**Hi team!
Congratulations:clap::clap:. Thank you for implementing all the changes requested by the last reviewer.
Before you go ahead and merge the PR. I will encourage you to implement the `Optional changes` highlighted in the PR below. This will make the project codebase looks more professional.**

Do have questions/comments? kindly drop them :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan.

2021-05-02 16:59 UTC, enaburekhan commented on app/views/layouts/application.html.erb
> +    <% end %>
**Optional**

- [ ] Move this logic to a helper. Views are only for rendering what's made available to them from the corresponding controller. And not for generating it.

2021-05-02 16:59 UTC, enaburekhan commented on app/views/users/profile.html.erb
> +  <% end %>
Also, move this logic to a helper.

2021-05-02 17:03 UTC, merged